import 'package:flutter/material.dart';
import 'package:stripling_wallet/utils/colors.dart';
import 'package:stripling_wallet/utils/constants.dart';
import 'package:stripling_wallet/welcome/signup.dart';

import 'components/form_label.dart';

class Authentication extends StatefulWidget {
  const Authentication({Key? key}) : super(key: key);

  @override
  State<Authentication> createState() => _AuthenticationState();
}

class _AuthenticationState extends State<Authentication> {
  final _formKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Container(
            padding: EdgeInsets.only(top: 20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.only(bottom: 30.0),
                  child: Container(
                    decoration: BoxDecoration(
                        color: Color.fromARGB(15, 22, 22, 22),
                        shape: BoxShape.circle),
                    child: IconButton(
                      icon: const Icon(Icons.arrow_back_ios_new),
                      color: Colors.black,
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    ),
                  ),
                ),
                const Text(
                  'Authentication',
                  style: TextStyle(fontSize: 24, fontWeight: FontWeight.w600),
                ),
                Container(
                  child: Padding(
                    padding: const EdgeInsets.only(top: 84.0),
                    child: Form(
                      key: _formKey,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          FormLabel(text: 'Child ID'),
                          TextFormField(
                            validator: (value) {
                              if (value == null || value.isEmpty) {
                                return 'Please enter some text';
                              }
                              return null;
                            },
                            decoration: MyConstants.formInputDecoration,
                          ),
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 8.0),
                            child: Text(
                              'This is an ID generated by your Parent',
                              style: TextStyle(
                                // color: Color(0xFF151920),
                                color: Colors.grey,
                              ),
                            ),
                          ),
                          // Padding(
                          //   padding: const EdgeInsets.symmetric(vertical: 16.0),
                          //   child: ElevatedButton(
                          //     onPressed: () {
                          //       // Validate returns true if the form is valid, or false otherwise.
                          //       if (_formKey.currentState!.validate()) {
                          //         // If the form is valid, display a snackbar. In the real world,
                          //         // you'd often call a server or save the information in a database.
                          //         ScaffoldMessenger.of(context).showSnackBar(
                          //           const SnackBar(
                          //               content: Text('Processing Data')),
                          //         );
                          //       }
                          //     },
                          //     child: const Text('Submit'),
                          //   ),
                          // ),
                          Padding(
                            padding: const EdgeInsets.only(top: 60.0),
                            child: SizedBox(
                              width: double.infinity,
                              height: 50,
                              child: DecoratedBox(
                                decoration: BoxDecoration(
                                  borderRadius: MyConstants.primaryBorderRadius,
                                  gradient: MyColors.primaryLinearGradient,
                                ),
                                child: ElevatedButton(
                                  onPressed: () {
                                    if (_formKey.currentState!.validate()) {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => SignUp()),
                                      );
                                    }
                                  },
                                  child: Text(
                                    'Submit',
                                    style: const TextStyle(
                                        fontWeight: FontWeight.w600),
                                  ),
                                  style: ElevatedButton.styleFrom(
                                      primary: Colors.transparent,
                                      elevation: 10),
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 30),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text('Don\'t have an ID? '),
                                // Spacer(),
                                GestureDetector(
                                  onTap: () {
                                    print('inviting parent');
                                  },
                                  child: Text(
                                    'Invite Parent',
                                    style: TextStyle(
                                        color: Color(0xFF3068A4),
                                        fontWeight: FontWeight.w600),
                                  ),
                                )
                              ],
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
